blogging/urls.py
from django.urls import path
from blogging.views import stub_view, detail_view, list_view, add_model
from blogging.feeds import LatestEntriesFeed

app_name = 'blogging'
urlpatterns = [
    path('', list_view, name="blog_index"),
    path('create', add_model, name="create_post"),
    path('posts/<int:post_id>/', detail_view, name="blog_detail"),
    path('latest/feed', LatestEntriesFeed(), name='feed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include  # <-- Make sure you have both of these imports.
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('polling/', include('polling.urls')),  # <-- Add this
    path('admin/', admin.site.urls),
    path('', include('blogging.urls', namespace='blogging')),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name="logout"),
]

polling/urls.py
from django.urls import path
from polling.views import list_view, detail_view

urlpatterns = [
    path('', list_view, name="poll_index"),
    path('polls/<int:poll_id>/', detail_view, name="poll_detail"),
]

blogging/models.py
from django.db import models  # <-- This is already in the file
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name='categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/forms.py
from django.forms import ModelForm
from blogging.models import Post


class MyPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', "author"]

blogging/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from blogging.models import Post
from blogging.forms import MyPostForm
from django.utils import timezone
from django import forms


def stub_view(request, *args, **kwargs):
    body = "Stub View\n\n"
    if args:
        body += "Args:\n"
        body += "\n".join(["\t%s" % a for a in args])
    if kwargs:
        body += "Kwargs:\n"
        body += "\n".join(["\t%s: %s" % i for i in kwargs.items()])
    return HttpResponse(body, content_type="text/plain")


def list_view(request):
    published = Post.objects.exclude(published_date__exact=None)
    posts = published.order_by('-published_date')
    context = {'posts': posts}
    return render(request,'blogging/list.html', context)


def detail_view(request, post_id):
    published = Post.objects.exclude(published_date__exact=None)
    try:
        post = published.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404
    context = {'post': post}
    return render(request, 'blogging/detail.html', context)


def add_model(request):

    if request.method == 'POST':
        form = MyPostForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.published_date = timezone.now()
            model_instance.save()
            return redirect('/')
    else:

        form = MyPostForm()

        return render(request, "blogging/my_template.html", {'form': form})

polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll


def list_view(request):
    context = {'polls': Poll.objects.all()}
    return render(request, 'polling/list.html', context)


def detail_view(request, poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404

    if request.method == "POST":
        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

    context = {'poll': poll}
    return render(request, 'polling/detail.html', context)

blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ post }}</h1>
<p class="byline">
  Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
</p>
<div class="post-body">
  {{ post.text }}
</div>
<ul class="categories">
  {% for category in post.categories.all %}
    <li>{{ category }}</li>
  {% endfor %}
</ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}
{% block content %}
  <h1>Recent Posts</h1>
  {% comment %} here is where the query happens {% endcomment %}
  {% for post in posts %}
  <div class="post">
  <h2>
    <a href="{% url 'blogging:blog_detail' post.pk %}">{{ post }}</a>
  </h2>
    <p class="byline">
      Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
      {{ post.text }}
    </div>
    <ul class="categories">
      {% for category in post.categories.all %}
        <li>{{ category }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endfor %}
{% endblock %}

blogging/templates/blogging/my_template.html
{% extends "base.html" %}

{% block content %}
<form method="post" >
{% csrf_token %}
{{form}}

<button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
  </head>
  <body>
    <div id="header">  {# header begins here #}
      <ul id="control-bar">
      <li><a href="{% url 'blogging:create_post' %}">Create Post</a></li>
      <li><a href="{% url 'blogging:blog_index' %}">Home</a></li>
      {% if user.is_authenticated %}
        {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
        <li><a href="{% url 'logout' %}">logout</a></li>
      {% else %}
        <li><a href="{% url 'login' %}">login</a></li>
      {% endif %}
      </ul>
    </div>              {# header ends here #}
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysite/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ poll.title }}</h1>
<div class="poll-body">
    {{ poll.text }}
</div>
<div class="poll-score">
    Current score: {{ poll.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in polls %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}